debug: false

logging:
  level:
    com.sparta.doing: debug
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

spring:
  datasource:
    url: jdbc:mysql://<host_name>:3306/<database_name>
    #    url: jdbc:h2:~/h2db/local
    username: <user_id>
    password: <password>
    driver-class-name: com.mysql.cj.jdbc.Driver
  h2:
    console:
      enabled: true
  jpa:
    open-in-view: false
    defer-datasource-initialization: true
    hibernate.ddl-auto: update
    show-sql: true
    #    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true
        check_nullability: true

jwt:
  header: Authorization
  #HS512 알고리즘 사용
  #64byte 이상의 secret key 필요
  #https://www.convertstring.com/ko/EncodeDecode/Base64Encode
  #text 'innovation-camp-in-dongjak-mini-project-innovation-camp-in-dongjak-mini-project-secret'을 base64로 인코딩
  secret: aW5ub3ZhdGlvbi1jYW1wLWluLWRvbmdqYWstbWluaS1wcm9qZWN0LWlubm92YXRpb24tY2FtcC1pbi1kb25namFrLW1pbmktcHJvamVjdC1zZWNyZXQK
  # 액세스 토큰 유효기간 2시간
  access-token-lifetime-in-seconds: 7200
  # 리프레쉬 토큰 유효기간 3시간
  refresh-token-lifetime-in-seconds: 10800